### ISSUE TITLE
Add functionality to pull historical intraday data with IEX as endpoint

### ISSUE THREAD

**Issue by dyus1983** [hydrosquall/tiingo-python#117]
* Tiingo Python version:0.6.0
* Python version:3.6
* Operating System:

### Description
Hi there!

Tiingo offers ability to get historical intraday data from IEX.
Please refer to: https://api.tiingo.com/docs/iex/realtime#historicalPriceData
Here is a request url example for historical 5-min data:
https://api.tiingo.com/iex/aapl/prices?startDate=2018-5-22&resampleFreq=5min

Availble frequencies are in minutes and hours.

Please add this functionality to tiingo-python

Thank you!
Dias

**Comment by hydrosquall** [comment]
Hi @dyus1983 ! Thanks for bringing this new endpoint to my attention, and for your interest in Tiingo. I'll look into adding this either this weekend or next, unless someone else is interested in picking this up.

**Comment by hydrosquall** [comment]
Released in #127

**Comment by jjw358** [comment]
hello, tiingo allows access to historical 1min volume which is iex platform volume. but cannot seem to get access to marketVolume, do u mind adding? thx a lot!

**Comment by tiingo** [comment]
@jjw358 Tiingo does not provide intraday total market volume, only volume via our connection to the IEX Exchange

**Comment by jjw358** [comment]
Thank you for your response! It seems like iex separates everything into
iex only and market wide. Are there any plans for tiingo to include market
wide information for intraday historical data in future releases?

Thanks!
