### ISSUE TITLE
[Feature] Add support for Tiingo Cryptocurrency Data Endpoint

### ISSUE THREAD

**Issue by hydrosquall** [hydrosquall/tiingo-python#135]
Tiingo supports over 1800 different crypto tickers.

The API Documentation is here: https://api.tiingo.com/docs/crypto/overview

**Comment by n1rna** [comment]
Hi, I am already working on this issue. Please assign to me.

**Comment by hydrosquall** [comment]
Closed by @n1rna in https://github.com/hydrosquall/tiingo-python/pull/340
