### ISSUE TITLE
[Feature Request][API] Support "write" functionality to a user's Tiingo watch list

### ISSUE THREAD

**Issue by 2firstnames** [hydrosquall/tiingo-python#160]
Hi guys! I am not sure if Tiingo API supports this functionality but a feature that I would consider invaluable would be the ability to add stocks to my Tiingo portfolio via passing tickers to the API. Thus my program could pick candidate stocks and add them to a daily watch list to track performance of various strategies.

**Comment by hydrosquall** [comment]
Hi @2firstnames,

Thanks for the suggestion. 

Currently, the public facing Tiingo API is "read-only", meaning that it only pulls data out of the Tiingo platform. However, I think that this could be a useful feature for other people as well - perhaps @tiingo might be able to weigh in on the feasibility of adding this in the near future.

**Comment by hydrosquall** [comment]
Closing this issue for now since the user-facing API doesn't support any write operations. We can reopen this if Tiingo opens ups this capability in the future.
