### ISSUE TITLE
Small News API Issues

### ISSUE THREAD

**Issue by scolemann** [hydrosquall/tiingo-python#317]
* Tiingo Python version: .10
* Python version: 3.6
* Operating System: Windows

### Description

The sources parameter does not work. It's named "sources", but the Tiingo API specifies "source".

The onlyWithTickers boolean parameter is in the Tiingo API, but not supported by the client.

**Comment by hydrosquall** [comment]
Hi @scolemann , thanks for reporting! I think this used to work, so perhaps there has been an API change. I'll make release some updates shortly.

**Comment by hydrosquall** [comment]
@scolemann the fixes have been released and are available in the latest tiingo `0.11.0` - feel free to reopen this thread if you need anything else.
