### ISSUE TITLE
Update Documentation with Basic Bugfixes

### ISSUE THREAD

**Issue by hydrosquall** [hydrosquall/tiingo-python#36]
This is a small change to the documentation that would make a great first PR!

- One of the examples is out of date, both `README.md` and the sphinx docs need updates

https://github.com/hydrosquall/tiingo-python/issues/31#issuecomment-338496729

- Add an example for pulling historical data to the `Readme.md` and the Sphinx docs. I've provided an example below. This is per a request received in the same thread linked to above.

https://github.com/hydrosquall/tiingo-python/issues/31#issuecomment-338511153

**Comment by maykillmore** [comment]
Can I take this up?

**Comment by hydrosquall** [comment]
@maykillmore : absolutely! Just fork this repository, make a development branch, and you should be good to go. Let me know if you have any questions!

**Comment by hydrosquall** [comment]
These were fixed in release `v0.4.2` https://github.com/hydrosquall/tiingo-python/commit/33b869031048f465e4c34b7a667ba9e8dd261f44 .
