### ISSUE TITLE
News permissions

### ISSUE THREAD

**Issue by Fux002** [hydrosquall/tiingo-python#37]
* Tiingo Python version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
when i run the news request i get this:

ERROR:root:{"detail":"You do not have permission to access the News API"}
403 Client Error: Forbidden for url: https://api.tiingo.com/tiingo/news?sources=washingtonpost.com&limit=100&sortBy=publishedDate&offset=0&endDate=2017-10-01&tickers=GOOGL&tags=machine+learning&startDate=2017-01-01
None

what permissions do i need to i need to be a paying member?

**Comment by hydrosquall** [comment]
Hey @Fux002 , the `news` API is a premium feature, but the historical pricing data is available for free. You can find the full breakdown of the difference between free/premium plans here: https://api.tiingo.com/pricing
