### ISSUE TITLE
[Feature][Request] Intraday Quotes

### ISSUE THREAD

**Issue by GenusGeoff** [hydrosquall/tiingo-python#465]
* Tiingo Python version: 0.12
* Python version: 3.7.6
* Operating System: Linux/Windows

### Description

Doesn't seem to permit connection to IEX streaming data.

The module works as expected except it doesn't seem to integrate the IEX functionality rather resting on the EOD Data.

### What I Did

N/A

**Comment by hydrosquall** [comment]
Hi @GenusGeoff,

Thanks for the feedback! Are you interested in the IEX [REST](https://api.tiingo.com/documentation/websockets/iex) data or the IEX [Streaming](https://api.tiingo.com/documentation/websockets/iex) data?

If you are looking for the streaming data, I don't think this library is a good fit. However, if you are interested in IEX REST data, we can look into that as a feature request for the next release.

**Comment by GenusGeoff** [comment]
REST is fine. I just need a reference point about every five-minutes or so.

WebSockets might be a bit much. I don't need that kind of data throughput--it's non-value added.

On Jun 2, 2020 9:15 PM, Cameron Yick <notifications@github.com> wrote:

Hi @GenusGeoff<https://github.com/GenusGeoff>,

Thanks for the feedback! Are you interested in the IEX REST<https://api.tiingo.com/documentation/websockets/iex> data or the IEX Streaming<https://api.tiingo.com/documentation/websockets/iex> data?

If you are looking for the streaming data, I don't think this library is a good fit. However, if you are interested in IEX REST data, we can look into that as a feature request for the next release.

**Comment by hydrosquall** [comment]
Hi @GenusGeoff ,

The good news is that this library currently does use the `IEX` endpoint if the `frequency` parameter is provided with a value smaller than `daily`.

https://github.com/hydrosquall/tiingo-python/blob/c034adb19027fc5a2a292ffad39bfe55b7787d4c/tiingo/api.py#L153-L167

If there are additional fields you'd expect in the response or options on the [docs](https://api.tiingo.com/documentation/iex) page that we don't expose yet inside the python library, feel free to make note of them here, and we'll add them.

**Comment by GenusGeoff** [comment]
From https://api.tiingo.com/documentation/iex

# To request top-of-book/last for all tickers, use the following REST endpoint
https://api.tiingo.com/iex

# To request top-of-book/last for specific tickers, use the following REST endpoint
https://api.tiingo.com/iex/<ticker>

This provides intraday last/top of book access. I'm working through the code a bit myself to see if I can integrate the functionality. I would, personally, find the feature very useful.

**Comment by GenusGeoff** [comment]
Some roughed-in code which I would need to seek to integrate with your code (I wrote a separate code base for now):

`
def colRename(myDict):
        ''' Reads a Pandas dataframe returned by Tiingo and renames the columns from generic integers into ticker column names '''
        colNames = {}
        for column in range(len(myDict.columns)):
                colNames[column] = myDict[column]['ticker']
        myDict.rename(columns = colNames, inplace = True)
        return myDict

def iex(tickers, afterHours, token):
        ''' Retrieves Tiingo Top of Book Intraday Quotes from IEX Endpoint '''
        requestResponse = requests.get("https://api.tiingo.com/iex/?tickers={}&afterHours={}&token={}".format(tickers, afterHours, token), headers=headers)
        myDict = pd.DataFrame.from_dict(requestResponse.json()).transpose()
        colRename(myDict)
        return myDict`
