### ISSUE TITLE
Data frequency resampling does not work

### ISSUE THREAD

**Issue by dyus1983** [hydrosquall/tiingo-python#52]
* Tiingo Python version: 0.4.1
* Python version: 3.6.3
* Operating System: Windows 10

### Description

Historical price data cannot be resampled to anything other than 'daily'.

### What I Did

```
from pandas.io.json import json_normalize
from tiingo import TiingoClient

client = TiingoClient(config)

msft_30m = client.get_ticker_price('MSFT', startDate='2017-12-01', endDate='2017-12-21', frequency='30min')

json_normalize(msft_hist)
```

> adjClose | adjHigh | adjLow | adjOpen | adjVolume | close | date | divCash | high | low | open | splitFactor | volume
> -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
> 84.26 | 84.8100 | 83.2200 | 83.60 | 29387325 | 84.26 | 2017-12-01T00:00:00.000Z | 0.0 | 84.8100 | 83.2200 | 83.60 | 1.0 | 29387325
> 81.08 | 84.4299 | 80.7000 | 84.42 | 37977732 | 81.08 | 2017-12-04T00:00:00.000Z | 0.0 | 84.4299 | 80.7000 | 84.42 | 1.0 | 37977732
> 81.59 | 82.6800 | 80.9801 | 81.34 | 25512120 | 81.59 | 2017-12-05T00:00:00.000Z | 0.0 | 82.6800 | 80.9801 | 81.34 | 1.0 | 25512120
> 82.78 | 83.1400 | 81.4300 | 81.55 | 24821403 | 82.78 | 2017-12-06T00:00:00.000Z | 0.0 | 83.1400 | 81.4300 | 81.55 | 1.0 | 24821403
> 82.49 | 82.8000 | 82.0000 | 82.54 | 20378114 | 82.49 | 2017-12-07T00:00:00.000Z | 0.0 | 82.8000 | 82.0000 | 82.54 | 1.0 | 20378114
> 84.16 | 84.5800 | 83.3300 | 83.63 | 23825056 | 84.16 | 2017-12-08T00:00:00.000Z | 0.0 | 84.5800 | 83.3300 | 83.63 | 1.0 | 23825056
> 85.23 | 85.3700 | 84.1200 | 84.29 | 19909119 | 85.23 | 2017-12-11T00:00:00.000Z | 0.0 | 85.3700 | 84.1200 | 84.29 | 1.0 | 19909119
> 85.58 | 86.0500 | 85.0800 | 85.31 | 23534946 | 85.58 | 2017-12-12T00:00:00.000Z | 0.0 | 86.0500 | 85.0800 | 85.31 | 1.0 | 23534946
> 85.35 | 86.0000 | 85.1700 | 85.74 | 21307911 | 85.35 | 2017-12-13T00:00:00.000Z | 0.0 | 86.0000 | 85.1700 | 85.74 | 1.0 | 21307911
> 84.69 | 85.8739 | 84.5300 | 85.43 | 19080106 | 84.69 | 2017-12-14T00:00:00.000Z | 0.0 | 85.8739 | 84.5300 | 85.43 | 1.0 | 19080106
> 86.85 | 87.0900 | 84.8800 | 85.26 | 52430167 | 86.85 | 2017-12-15T00:00:00.000Z | 0.0 | 87.0900 | 84.8800 | 85.26 | 1.0 | 52430167
> 86.38 | 87.4999 | 86.2300 | 87.12 | 21551076 | 86.38 | 2017-12-18T00:00:00.000Z | 0.0 | 87.4999 | 86.2300 | 87.12 | 1.0 | 21551076
> 85.83 | 86.3500 | 85.2700 | 86.35 | 23241979 | 85.83 | 2017-12-19T00:00:00.000Z | 0.0 | 86.3500 | 85.2700 | 86.35 | 1.0 | 23241979
> 85.52 | 86.3000 | 84.7100 | 86.20 | 23425009 | 85.52 | 2017-12-20T00:00:00.000Z | 0.0 | 86.3000 | 84.7100 | 86.20 | 1.0 | 23425009
> 85.50 | 86.1000 | 85.4000 | 86.05 | 17939766 | 85.50 | 2017-12-21T00:00:00.000Z | 0.0 | 86.1000 | 85.4000 | 86.05 | 1.0 | 17939766

**Comment by Yoshi9143** [comment]
Hi, intraday resampling is not available for the EOD data. For end-of-day data, the highest resolution is 1 day. You can resample to weekly, monthly, and annually as per the docs.

https://api.tiingo.com/docs/tiingo/overview
![image](https://user-images.githubusercontent.com/160189/34307888-6e0d378c-e718-11e7-8c77-fcac5daea419.png)

**Comment by dyus1983** [comment]
Ok, I see. Thank you!
