### ISSUE TITLE
[Enhancement] Add option to request data in csv format in get_dataframe method

### ISSUE THREAD

**Issue by 2xmm** [hydrosquall/tiingo-python#523]
* Tiingo Python version: 0.12
* Python version: 3.8.5
* Operating System: macOS 10.14.6

### Description

Hi, I noticed in the tiingo docs they mention that a csv response is 4-5x faster than json (https://api.tiingo.com/documentation/general/overview -- 1.1.4 Response Formats). 

Fetching data in csv format is implemented in `get_ticker_price` but not `get_dataframe`. 

I've made the changes on my end adding a `fmt` paramerter to `get_dataframe` which can be set to `csv`. If you like, I'm happy to put together a pull request with these changes.

### What I Did

N/A

**Comment by hydrosquall** [comment]
Hi @2xmm ,

I didn't know about that performance difference- that's terrific to know! I would be very glad to see this capability added to the library, thank you for reaching out. Your proposed solution sounds good + consistent with the design of other parts of the library.

There's a short guide about how to get started with a local development environment here: https://github.com/hydrosquall/tiingo-python/blob/master/CONTRIBUTING.rst#get-started

Let me know if you have any questions!

**Comment by 2xmm** [comment]
Hi @hydrosquall, I've submitted the pull request and everything looks good so far. I noticed my vcrpy fixtures look different than the ones in the repo. Not sure why that is.

**Comment by hydrosquall** [comment]
Fixed by #524
