### ISSUE TITLE
get_news() fails when no sources are specified.

### ISSUE THREAD

**Issue by minnend** [hydrosquall/tiingo-python#566]
* Tiingo Python version: 0.13.0
* Python version: 3.9
* Operating System: Windows (PyCharm environment)

### Description

Goal: Pull tiingo news articles without a `sources` filter.
Result: Request was ok (code=200) but there were no articles.

### What I Did

The bug appears to be in how `sources` is handled. By default, sources=[] in the get_news() function. Then the code sets a request parameter like this:

'source': (",").join(sources)

which resolves to params["source"] = "". Tiingo responds to the request with zero articles. It's easy to verify the behavior through direct links:

https://api.tiingo.com/tiingo/news?tickers=aapl,googl&source=&limit=10 <--- response = []
https://api.tiingo.com/tiingo/news?tickers=aapl,googl&limit=10  <---- response = 10 articles in JSON format

The fix is simple. Just change line 341 in api.py to:

'source': (",").join(sources) if sources else None,

Ideally, the unit tests should also be updated to test for correct behavior with empty parameters. I'll work on a pull-request or feel free to make the one line change and close this issue. :)

**Comment by hydrosquall** [comment]
Thanks for the detailed bug report, finding the solution, and offering to help out with a PR! As you identified the fix, I'd be delighted to review your PR. Feel free to add your name to the `CONTRIBUTORS.rst` when you do.

**Comment by hydrosquall** [comment]
Fixed by @minnend in #569
