### ISSUE TITLE
Index Data?

### ISSUE THREAD

**Issue by craigmediaservices** [hydrosquall/tiingo-python#642]
Not really a bug, just a question:

Is there anyway to directly access index data (e.g. NASDAQ, S&P500) without using a ETF (e.g. SPY)? It looks like it should be possible, but not clear how.

**Comment by tiingo** [comment]
We do not offer index data, the licensing for this data can be complicated as it typically requires a license between you and the exchange dissemination firm, along with a license fee you would pay directly to them.

**Comment by craigmediaservices** [comment]
Thank you for the fast reply!
