### ISSUE TITLE
Multiple tags using Tiingo News API

### ISSUE THREAD

**Issue by rampager525** [hydrosquall/tiingo-python#769]
* Tiingo Python version: Latest
* Python version: Latest
* Operating System: Mac OS Monterey

Is it possible to use multiple tags in the Tiingo News API, and also logical operators such as 'AND' and 'OR' with the multiple tags ?

Examples: 
- Prompting the API to return news with the tags 'tax' & 'UK' & 'Liz Truss' 
-  Prompting the API to return news with the tags 'Energy crisis' & ('Germany' OR 'Europe') 

If the examples above are possible, please also attach the example code. Much appreciated, thanks.

**Comment by hydrosquall** [comment]
Hi, the official documentation https://api.tiingo.com/documentation/news . 

I don't think custom boolean operators are supported yet, but you could send it as a feature request to the email address at the linked page. I'm not sure whether the current behavior is an implicit AND or OR.

Your code snippet might look something like this:

```python
articles = client.get_news(tickers=[],
                            tags=['tax', 'uk', 'liz truss'],
                            startDate='2022-06-01',
                            endDate='2022-08-01')
```
